name: Code Scan

on:
  push:
    branches:
      - main
      - v2
  pull_request:
    branches:
      - main
      - v2
  workflow_dispatch:

jobs:
  fossa:
    name: FOSSA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.X
      - name: Fake Install flux
        run: mkdir -p pkg/flux/bin && touch pkg/flux/bin/flux
      - name: Fake dist for the ui cmd
        run: mkdir -p cmd/gitops/ui/run/dist && touch cmd/gitops/ui/run/dist/index.js
      - name: Run FOSSA scan and upload build data
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
          github-token: ${{ github.token }}

  snyk-sourcecode:
    name: Snyk Sourcecode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17'
      - name: Generate UI file to embed
        run: mkdir -p cmd/gitops/ui/run/dist && touch cmd/gitops/ui/run/dist/index.html
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --sarif-file-output=snyk.code.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        continue-on-error: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.code.sarif
      - name: Upload a report to Snyk to report new vulnerabilities
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        if: ${{ github.event_name == 'push' }}

  snyk-docker:
    name: Snyk Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stoml
        run: make dependencies
      - name: Build docker image
        run: make docker
      - name: Scan docker image
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        with:
          image: ghcr.io/weaveworks/wego-app:latest
          args: --file=Dockerfile
        continue-on-error: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      - name: Upload result to Snyk
        uses: snyk/actions/docker@master
        with:
          command: monitor
          image: ghcr.io/weaveworks/wego-app:latest
          args: --file=Dockerfile
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_TOKEN }}
        if: ${{ github.event_name == 'push' }}
