on:
  push:
    paths-ignore:
      - "doc/**"
    branches:
      - v2
  pull_request:
    branches:
      - v2
  workflow_dispatch:

name: V2 CI Workflow
jobs:
  ci-js:
    name: V2 CI Check JS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.2]
    steps:
      - uses: actions/checkout@v2
      - name: Node modules cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: make dependencies
      - run: make node_modules
      - run: make ui-audit
      - run: make ui
      - run: make ui-lint
      - run: make ui-test
  ci-go:
    name: V2 CI Check Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.17.5]
    steps:
      - uses: actions/checkout@v2
      - name: Go modules cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up kubebuilder
        uses: fluxcd/pkg/actions/kubebuilder@main
      - run: make dependencies
      - run: go mod download
      - run: make lint
      - run: make gitops
      - run: make gitops-server
      - run: make unit-tests
      # - run: make lib-test

  full-ci:
    name: V2 CI Check (16.13.2, 1.17.5)
    runs-on: ubuntu-latest
    needs: [ci-go, ci-js]
    steps:
      - run: echo "All done"
